title: Kwangjin Yoon
author: Kwangjin Yoon
email: yoon28@gmail.com
description: personal web-page
twitter_username: 
github_username: yoon28

disqus:
  shortname: yoon28
google_analytics: "UA-83877055-2"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#  - about.html

# Build settings
plugins:
  - jekyll-seo-tag
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock